server.port=8080

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/user_management
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.tonentreprise.backend=DEBUG

# Configuration Email Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mloukamalek931@gmail.com
spring.mail.password=yyns smuc nmps rbbt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Configuration OpenAI
openai.api.key=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
tavily.api.key=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


# --- Microservice Python OCR ---
ocr.service.url=http://localhost:8000
ocr.service.connect-timeout=5000
ocr.service.read-timeout=60000

# --- Multipart (upload PDF depuis Angular) ---
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB
