name: CI/CD
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    uses: khaoulahamza/devops-templates/.github/workflows/deploy.yml@main
    secrets:
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
