name: CI/CD Déploiement

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choisir l environnement de déploiement'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  call-deploy:
    uses: winddevops-org/devops-templates/.github/workflows/mono-pipeline.yml@main
    with:
      environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'staging' }}
      ingress_domain: ${{ vars.INGRESS_DOMAIN }}
    secrets:
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
